### ISSUE TITLE
Samtools sort error (line 1825)

### ISSUE THREAD

**Issue by nickp60** [jamesabbott/BugBuilder#13]
Hi there!  Just a quick heads up: I got an error thrown from samtools sort command on line 1825;  it probably has to do with my version of samtools (1.3.1) but I needed to change the following line:
    `$cmd = "$samtools_dir/samtools view -q 10 -Sb $tmpdir/bwa/$reference.sam 2>$tmpdir/bwa/samtoolsview.log"`
    `# . "|$samtools_dir/samtools sort - $tmpdir/bwa/$reference";`  #the old line
    `. "|$samtools_dir/samtools sort - > $tmpdir/bwa/$reference.bam";`

Thanks for all you do!

Running on ubuntu 14, cloned from github

**Comment by jamesabbott** [comment]
Thanks - looks like samtools behaviour has changed. This should be fixed in commit 43f22e4 

James
